name: flutter_screen_recorder
description: Flutter session replay plugin with native Android and iOS view-hierarchy capture, interaction telemetry, logs, and custom events.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hubhive.flutter_screen_recorder
        pluginClass: FlutterScreenRecorderPlugin
      ios:
        pluginClass: FlutterScreenRecorderPlugin
